name: Actualizar Calendario

on:
  push: # <--- ESTO ACTIVA LA EJECUCIÓN AL HACER PUSH
    branches:
      - main # O 'master', dependiendo de cómo se llame tu rama principal
  schedule:
    - cron: "0 23 * * *" # 23:00 UTC = 00:00 CET (Winter) / 01:00 CEST (Summer)
  workflow_dispatch: # Permite ejecutarlo manualmente con un botón

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar librerías
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script de calendario
        run: python update_calendar.py

      - name: Guardar cambios (Commit & Push)
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add cv_bunyola.ics
          # Solo hace commit si hay cambios
          git diff --quiet && git diff --staged --quiet || (git commit -m "Actualizar calendario automático" && git push)
